// Fetch Issues Request
export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAILURE = 'FETCH_ISSUES_REQUEST';

// Fetch Issue by ID Request
export const FETCH_ISSUE_BY_ID_REQUEST = 'FETCH_ISSUE_BY_ID_REQUEST';
export const FETCH_ISSUE_BY_ID_SUCCESS = 'FETCH_ISSUE_BY_ID_SUCCESS';
export const FETCH_ISSUE_BY_ID_FAILURE = 'FETCH_ISSUE_BY_ID_FAILURE';

// Create Issue Request
export const CREATE_ISSUE_REQUEST = 'CREATE_ISSUE_REQUEST';
export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';
export const CREATE_ISSUE_FAILURE = 'CREATE_ISSUE_FAILURE';

// Update Issue Status Request
export const UPDATE_ISSUE_STATUS_REQUEST = 'UPDATE_ISSUE_STATUS_REQUEST';
export const UPDATE_ISSUE_STATUS_SUCCESS = 'UPDATE_ISSUE_STATUS_SUCCESS';
export const UPDATE_ISSUE_STATUS_FAILURE = 'UPDATE_ISSUE_STATUS_FAILURE';

// Delete Issue Request
export const DELETE_ISSUE_REQUEST = 'DELETE_ISSUE_REQUEST';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS';
export const DELETE_ISSUE_FAILURE = 'DELETE_ISSUE_FAILURE';

// Assign User to Issue Request
export const ASSIGN_USER_TO_ISSUE_REQUEST = 'ASSIGN_USER_TO_ISSUE_REQUEST';
export const ASSIGN_USER_TO_ISSUE_SUCCESS = 'ASSIGN_USER_TO_ISSUE_SUCCESS';
export const ASSIGN_USER_TO_ISSUE_FAILURE = 'ASSIGN_USER_TO_ISSUE_FAILURE';